project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"

website:
  title: "竹田研究室（Takeda Lab.）"
  navbar:
    left:
      - href: index.qmd
        text: ホームページ
      - href: 01_about/index.qmd
        text: 所在地
      - href: 02_resume/index.qmd
        text: 教員
      - href: 03_lecture/index.qmd
        text: 授業
      - href: 04_research/index.qmd
        text: 研究

format:
  html:
    theme:
      - cosmo
      - brand
    css: [css/styles.css, css/slide.scss]
    toc: true
