project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - 01_about/about.qmd
    - 02_resume/resume.qmd
    - 03_lecture/lecture.qmd
    - 04_research/research.qmd
    - topic*.qmd

website:
  title: "竹田研究室（Takeda Lab.）"
  navbar:
    left:
      - href: index.qmd
        text: ホームページ
      - href: 01_about/about.qmd
        text: 所在地
      - href: 02_resume/resume.qmd
        text: 教員
      - href: 03_lecture/lecture.qmd
        text: 授業
      - href: 04_research/research.qmd
        text: 研究

format:
  html:
    theme:
      - cosmo
      - brand
    css: [css/styles.css, css/lec.scss]
    toc: true



